INSERT INTO flashcards (front, back, set_id) VALUES
('apple', 'jabłko', 1),
('banana', 'banan', 1),
('cat', 'kot', 1),
('dog', 'pies', 1),
('house', 'dom', 1),
('car', 'samochód', 1),
('book', 'książka', 1),
('pen', 'długopis', 1),
('table', 'stół', 1),
('chair', 'krzesło', 1),
('window', 'okno', 1),
('door', 'drzwi', 1),
('shoe', 'but', 1),
('shirt', 'koszula', 1),
('pants', 'spodnie', 1),
('hat', 'czapka', 1),
('watch', 'zegarek', 1),
('bag', 'torba', 1),
('phone', 'telefon', 1),
('camera', 'aparat', 1),
('computer', 'komputer', 1),
('television', 'telewizor', 1),
('refrigerator', 'lodówka', 1),
('oven', 'piekarnik', 1),
('stove', 'kuchenka', 1),
('sink', 'zlew', 1),
('bed', 'łóżko', 1),
('sofa', 'kanapa', 1),
('lamp', 'lampa', 1),
('clock', 'zegar', 1),
('mirror', 'lustro', 1),
('painting', 'obraz', 1),
('carpet', 'dywan', 1),
('curtain', 'firanka', 1),
('shelf', 'półka', 1),
('drawer', 'szuflada', 1),
('desk', 'biurko', 1),
('tablecloth', 'obrus', 1),
('cup', 'kubek', 1),
('plate', 'talerz', 1),
('fork', 'widelc', 1),
('knife', 'nóż', 1),
('spoon', 'łyżka', 1),
('glass', 'szklanka', 1),
('bowl', 'miska', 1),
('pot', 'garnek', 1),
('pan', 'patelnia', 1),
('toaster', 'toster', 1),
('microwave', 'mikrofalówka', 1),
('blender', 'blender', 1),
('coffee maker', 'ekspres do kawy', 1),
('kettle', 'czajnik', 1),
('towel', 'ręcznik', 1),
('soap', 'mydło', 1),
('shampoo', 'szampon', 1),
('toothbrush', 'szczoteczka', 1),
('toothpaste', 'pasta do zębów', 1),
('razor', 'maszynka do golenia', 1),
('comb', 'grzebień', 1),
('brush', 'szczotka', 1),
('mirror', 'lustro', 1),
('hair dryer', 'suszarka do włosów', 1),
('vacuum cleaner', 'odkurzacz', 1),
('iron', 'żelazko', 1),
('hair straightener', 'prostownica', 1),
('scissors', 'nożyczki', 1),
('needle', 'igła', 1),
('thread', 'nitka', 1),
('buttons', 'guziki', 1),
('sewing machine', 'maszyna do szycia', 1),
('glue', 'klej', 1),
('tape', 'taśma', 1),
('stapler', 'zszywacz', 1),
('folder', 'folder', 1),
('notebook', 'zeszyt', 1),
('calculator', 'kalkulator', 1),
('pen', 'długopis', 1),
('pencil', 'ołówek', 1),
('eraser', 'gumka', 1),
('sharpener', 'temperówka', 1),
('ruler', 'linijka', 1),
('paint', 'farba', 1),
('brush', 'pędzel', 1),
('palette', 'paleta', 1),
('easel', 'sztaluga', 1),
('canvas', 'płótno', 1),
('frame', 'ramka', 1),
('sculpture', 'rzeźba', 1),
('statue', 'posąg', 1),
('monument', 'pomnik', 1),
('fountain', 'fontanna', 1),
('garden', 'ogród', 1),
('park', 'park', 1),
('bench', 'ławka', 1),
('bridge', 'most', 1),
('river', 'rzeka', 1),
('lake', 'jezioro', 1),
('mountain', 'góra', 1),
('forest', 'las', 1),
('desert', 'pustynia', 1),
('beach', 'plaża', 1),
('sea', 'morze', 1),
('ocean', 'ocean', 1),
('island', 'wyspa', 1),
('cave', 'jaskinia', 1),
('hill', 'wzgórze', 1),
('valley', 'dolina', 1),
('plateau', 'płaskowyż', 1),
('canyon', 'kanion', 1),
('waterfall', 'wodospad', 1),
('gorge', 'wąwóz', 1),
('riverbank', 'brzeg rzeki', 1),
('cliff', 'urwisko', 1),
('reef', 'rafa', 1),
('coral', 'korale', 1),
('shell', 'muszla', 1),
('starfish', 'rozgwiazda', 1),
('seaweed', 'wodorosty', 1),
('sand', 'piasek', 1),
('rock', 'skała', 1),
('mud', 'błoto', 1),
('soil', 'gleba', 1),
('hill', 'wzgórze', 1),
('sun', 'słońce', 1),
('moon', 'księżyc', 1),
('cloud', 'chmura', 1),
('rain', 'deszcz', 1),
('snow', 'śnieg', 1),
('wind', 'wiatr', 1),
('storm', 'burza', 1),
('thunder', 'grzmot', 1),
('lightning', 'błyskawica', 1),
('fog', 'mgła', 1),
('hurricane', 'huragan', 1),
('tornado', 'tornado', 1),
('earthquake', 'trzęsienie ziemi', 1),
('volcano', 'wulkan', 1),
('lava', 'lawa', 1),
('magma', 'magma', 1),
('crater', 'krater', 1),
('eruption', 'wybuch', 1),
('geysers', 'gejzery', 1),
('hot spring', 'gorące źródło', 1),
('spring', 'źródło', 1),
('water', 'woda', 1),
('ice', 'lód', 1),
('steam', 'para', 1),
('mist', 'mgiełka', 1),
('dew', 'rosa', 1),
('frost', 'szron', 1),
('hail', 'grad', 1),
('drizzle', 'mżawka', 1),
('sleet', 'deszcz ze śniegiem', 1),
('downpour', 'ulewa', 1),
('shower', 'prysznic', 1),
('forecast', 'prognoza', 1),
('weather', 'pogoda', 1),
('climate', 'klimat', 1),
('temperature', 'temperatura', 1),
('humidity', 'wilgotność', 1),
('pressure', 'ciśnienie', 1),
('barometer', 'barometr', 1),
('thermometer', 'termometr', 1),
('hygrometer', 'higrometr', 1),
('weather vane', 'wiej', 1),
('weather balloon', 'balon meteorologiczny', 1),
('weather station', 'stacja meteorologiczna', 1),
('weather map', 'mapa pogodowa', 1),
('weather satellite', 'satelita meteorologiczny', 1),
('weather radar', 'radar pogodowy', 1),
('weather model', 'model pogodowy', 1),
('weather app', 'aplikacja pogodowa', 1),
('weather report', 'raport pogodowy', 1),
('weather forecast', 'prognoza pogody', 1),
('weather warning', 'ostrzeżenie pogodowe', 1),
('weather alert', 'alarm pogodowy', 1),
('weather condition', 'warunki pogodowe', 1),
('weather change', 'zmiana pogody', 1),
('weather pattern', 'wzór pogodowy', 1),
('weather event', 'wydarzenie pogodowe', 1),
('weather phenomenon', 'zjawisko pogodowe', 1),
('weather system', 'system pogodowy', 1),
('weather map', 'mapa pogodowa', 1),
('weather satellite image', 'zdjęcie satelitarne', 1),
('weather radar image', 'zdjęcie radarowe', 1),
('weather station data', 'dane ze stacji meteorologicznej', 1),
('weather observation', 'obserwacja pogodowa', 1),
('weather measurement', 'pomiar pogodowy', 1),
('weather tracking', 'śledzenie pogody', 1),
('weather analysis', 'analiza pogody', 1),
('weather prediction', 'przewidywanie pogody', 1),
('weather simulation', 'symulacja pogody', 1),
('weather forecasting', 'prognozowanie pogody', 1),
('weather modeling', 'modelowanie pogody', 1),
('weather science', 'nauka o pogodzie', 1),
('weather technology', 'technologia pogodowa', 1),
('weather research', 'badania pogodowe', 1),
('weather data', 'dane pogodowe', 1),
('weather information', 'informacje pogodowe', 1),
('weather communication', 'komunikacja pogodowa', 1);



-----------------------------------------------
INSERT INTO flashcards (front, back, set_id) VALUES
('to be', 'być', 2),
('to have', 'mieć', 2),
('to do', 'robić', 2),
('to go', 'iść', 2),
('to make', 'robić', 2),
('to take', 'brać', 2),
('to come', 'przyjść', 2),
('to see', 'widzieć', 2),
('to know', 'wiedzieć', 2),
('to get', 'dostać', 2),
('to give', 'dawać', 2),
('to say', 'mówić', 2),
('to use', 'używać', 2);

-----------------------------------------------
INSERT INTO flashcards (front, back, set_id) VALUES
('Guten Morgen', 'Dzień dobry', 3),
('Guten Abend', 'Dobry wieczór', 3),
('Wie geht es Ihnen?', 'Jak się pan/pani ma?', 3),
('Ich danke Ihnen', 'Dziękuję', 3),
('Bitte schön', 'Proszę bardzo', 3),
('Entschuldigung', 'Przepraszam', 3),
('Könnten Sie bitte...? ', 'Czy mógłby pan/pani...? ', 3),
('Wo ist die Toilette?', 'Gdzie jest toaleta?', 3),
('Haben Sie eine Empfehlung?', 'Czy ma pan/pani jakąś rekomendację?', 3),
('Ich verstehe nicht', 'Nie rozumiem', 3);

-----------------------------------------------
INSERT INTO flashcards (front, back, set_id) VALUES
('hello', 'cześć', 4),
('goodbye', 'do widzenia', 4),
('please', 'proszę', 4),
('thank you', 'dziękuję', 4),
('sorry', 'przepraszam', 4),
('yes', 'tak', 4),
('no', 'nie', 4),
('maybe', 'może', 4),
('please repeat', 'proszę powtórzyć', 4),
('slowly', 'wolniej', 4),
('louder', 'głośniej', 4),
('quietly', 'ciszej', 4),
('now', 'teraz', 4),
('later', 'później', 4),
('today', 'dzisiaj', 4),
('tomorrow', 'jutro', 4),
('yesterday', 'wczoraj', 4),
('morning', 'rano', 4),
('afternoon', 'popołudnie', 4),
('evening', 'wieczór', 4);

-----------------------------------------------
INSERT INTO flashcards (front, back, set_id) VALUES
('Hola', 'Cześć', 5),
('Buenos días', 'Dzień dobry', 5),
('Buenas tardes', 'Dobry wieczór', 5),
('Buenas noches', 'Dobranoc', 5),
('Por favor', 'Proszę', 5),
('Gracias', 'Dziękuję', 5),
('Lo siento', 'Przepraszam', 5),
('¿Cómo estás?', 'Jak się masz?', 5);

-----------------------------------------------
