INSERT INTO sets (set_id, set_name, user_id, created_at) VALUES 
(1, 'Matematyka Podstawowa', 4, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(2, 'Biologia Klasa 8', 4, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(3, 'Historia Starożytna', 1, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(4, 'Angielski B1', 6, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(5, 'Geografia Świata', 9, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(6, 'Chemia Organiczna', 8, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(7, 'Fizyka dla Początkujących', 7, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(8, 'Literatura Polska', 5, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(9, 'Programowanie w Pythonie', 8, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(10, 'Ekonomia Podstawowa', 1, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(11, 'Hiszpański dla Początkujących', 6, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(12, 'Geometria', 5, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(13, 'Biochemia', 5, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(14, 'Historia Nowożytna', 8, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(15, 'Filozofia', 8, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(16, 'Francuski A2', 6, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(17, 'Język Polski', 7, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(18, 'Marketing Internetowy', 6, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(19, 'Analiza Matematyczna', 6, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(20, 'Biologia Klasa 7', 7, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(21, 'Chemia Nieorganiczna', 4, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(22, 'Literatura Angielska', 1, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(23, 'WOS', 3, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(24, 'Prawo Cywilne', 2, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(25, 'Zoologia', 5, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(26, 'Etyka', 7, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(27, 'Astronomia', 8, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(28, 'Socjologia', 4, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(29, 'Niemiecki B2', 10, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(30, 'Anatomia Człowieka', 8, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(31, 'Historia Średniowieczna', 8, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(32, 'Język Hiszpański', 7, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(33, 'Matematyka dla Inżynierów', 4, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(34, 'Biotechnologia', 8, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(35, 'Statystyka', 2, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(36, 'Historia Sztuki', 3, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(37, 'Fizyka Kwantowa', 6, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(38, 'Matematyka Dyskretna', 9, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(39, 'Historia Polski', 2, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(40, 'Biologia Molekularna', 7, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(41, 'Genetyka', 4, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(42, 'Prawo Karne', 7, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(43, 'Mikrobiologia', 7, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(44, 'Literatura Francuska', 7, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(45, 'Zoologia', 5, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(46, 'Robotyka', 7, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(47, 'Nanotechnologia', 5, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(48, 'Psychologia', 4, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(49, 'Biologia Roślin', 10, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(50, 'Ekologia', 3, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(51, 'Systemy Operacyjne', 5, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(52, 'Architektura Komputerowa', 10, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(53, 'Zoologia', 7, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(54, 'Pediatria', 3, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(55, 'Programowanie w C++', 9, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(56, 'Wprowadzenie do Informatyki', 2, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(57, 'Anatomia Zwierząt', 3, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(58, 'Robotyka', 6, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(59, 'Sztuczna Inteligencja', 6, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(60, 'Sieci Komputerowe', 4, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(61, 'Matematyka Finansowa', 5, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(62, 'Programowanie w Javie', 8, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(63, 'Inżynieria Oprogramowania', 1, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(64, 'Matematyka Dyskretna', 5, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(65, 'Analiza Matematyczna', 2, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(66, 'Historia Starożytna', 6, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(67, 'Mikroekonomia', 2, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(68, 'Literatura Angielska', 1, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(69, 'Robotyka', 4, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(70, 'Język Niemiecki', 3, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(71, 'Prawo Handlowe', 10, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(72, 'Historia Średniowieczna', 4, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(73, 'Analiza Matematyczna', 2, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(74, 'Zoologia', 2, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(75, 'Programowanie w PHP', 1, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(76, 'Ekonomia Podstawowa', 4, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(77, 'Historia Nowożytna', 6, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(78, 'Robotyka', 2, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(79, 'Astronomia', 6, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(80, 'Mikrobiologia', 8, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(81, 'Programowanie w SQL', 1, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(82, 'Literatura Niemiecka', 2, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(83, 'Historia Średniowieczna', 10, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(84, 'Historia Sztuki', 9, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(85, 'Genetyka', 6, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(86, 'Francuski B1', 9, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(87, 'Historia Ameryki', 6, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(88, 'Historia Sztuki', 2, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(89, 'Programowanie w Pythonie', 10, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(90, 'Programowanie w C#', 6, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(91, 'Literatura Polska', 1, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(92, 'Literatura Angielska', 4, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(93, 'Ekonomia', 5, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(94, 'Prawo Karne', 4, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(95, 'Geometria', 3, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(96, 'Analiza Matematyczna', 2, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(97, 'Programowanie w Kotlinie', 8, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(98, 'Literatura Niemiecka', 8, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(99, 'Historia Francji', 3, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(100, 'Filozofia', 6, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(101, 'Fizyka Klasyczna', 10, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(102, 'Historia Europy', 3, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(103, 'Literatura Angielska', 7, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(104, 'Historia Starożytna', 1, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(105, 'Psychologia', 6, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(106, 'Matematyka Finansowa', 2, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(107, 'Historia Nowożytna', 9, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(108, 'Mikrobiologia', 4, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(109, 'Programowanie w C++', 8, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(110, 'Historia Polski', 5, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(111, 'Geografia Świata', 6, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(112, 'Matematyka Dyskretna', 6, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(113, 'Robotyka', 5, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(114, 'Programowanie w Kotlinie', 7, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(115, 'Prawo Administracyjne', 3, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(116, 'Etyka', 3, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(117, 'Zoologia', 10, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(118, 'Geografia Świata', 2, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(119, 'Biochemia', 5, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval),
(120, 'Chemia Organiczna', 4, CURRENT_TIMESTAMP - (random() * 90) * '1 day'::interval);
